import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface OrderItem {
    id: number;
    name: string;
    sku: string;
    price: string;
    quantity: number;
    total: string;
}

interface Customer {
    name: string;
    email: string;
    phone: string;
    address: string;
}

interface TimelineEvent {
    id: number;
    action: string;
    description: string;
    time: string;
}

interface Order {
    id: string;
    customer: Customer;
    status: string;
    createdAt: string;
    updatedAt: string;
    paymentMethod: string;
    paymentStatus: string;
    shippingMethod: string;
    shippingAddress: string;
    notes: string;
    items: OrderItem[];
    subtotal: string;
    shipping: string;
    tax: string;
    total: string;
    timeline: TimelineEvent[];
}

export function generateInvoicePDF(order: Order): void {
    const doc = new jsPDF();

    // Colors
    const primaryColor: [number, number, number] = [59, 130, 246]; // Blue
    const textColor: [number, number, number] = [31, 41, 55]; // Dark gray
    const lightGray: [number, number, number] = [156, 163, 175];

    // Header - Company Name
    doc.setFontSize(24);
    doc.setTextColor(...primaryColor);
    doc.text('INVOICE', 20, 25);

    // Invoice Number & Date
    doc.setFontSize(10);
    doc.setTextColor(...lightGray);
    doc.text(`Invoice #: INV-${order.id.replace('ORD-', '')}`, 20, 35);
    doc.text(`Date: ${order.createdAt}`, 20, 40);
    doc.text(`Status: ${order.paymentStatus.toUpperCase()}`, 20, 45);

    // Bill To Section
    doc.setFontSize(12);
    doc.setTextColor(...textColor);
    doc.text('Bill To:', 20, 60);

    doc.setFontSize(10);
    doc.text(order.customer.name, 20, 68);
    doc.text(order.customer.email, 20, 74);
    doc.text(order.customer.phone, 20, 80);

    // Split address if too long
    const addressLines = doc.splitTextToSize(order.customer.address, 80);
    doc.text(addressLines, 20, 86);

    // Ship To Section
    doc.setFontSize(12);
    doc.text('Ship To:', 120, 60);

    doc.setFontSize(10);
    const shipAddressLines = doc.splitTextToSize(order.shippingAddress, 70);
    doc.text(shipAddressLines, 120, 68);

    // Payment Info
    doc.setFontSize(12);
    doc.text('Payment Info:', 120, 90);
    doc.setFontSize(10);
    doc.text(`Method: ${order.paymentMethod}`, 120, 98);
    doc.text(`Status: ${order.paymentStatus}`, 120, 104);

    // Items Table
    const tableData = order.items.map(item => [
        item.name,
        item.sku,
        item.price,
        item.quantity.toString(),
        item.total
    ]);

    autoTable(doc, {
        startY: 115,
        head: [['Product', 'SKU', 'Price', 'Qty', 'Total']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: primaryColor,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: {
            fontSize: 9,
            cellPadding: 4,
        },
        columnStyles: {
            0: { cellWidth: 60 },
            1: { cellWidth: 30 },
            2: { cellWidth: 25, halign: 'right' },
            3: { cellWidth: 15, halign: 'center' },
            4: { cellWidth: 25, halign: 'right' },
        },
    });

    // Get the final Y position after the table
    const finalY = (doc as any).lastAutoTable.finalY + 10;

    // Order Summary
    doc.setFontSize(10);
    doc.setTextColor(...textColor);

    // Right-align the summary
    const summaryX = 140;
    const valueX = 175;

    // Subtotal
    doc.text('Subtotal:', summaryX, finalY);
    doc.text(order.subtotal, valueX, finalY, { align: 'right' });

    // Shipping
    doc.text('Shipping:', summaryX, finalY + 7);
    doc.text(order.shipping, valueX, finalY + 7, { align: 'right' });

    // Tax
    doc.text('Tax:', summaryX, finalY + 14);
    doc.text(order.tax, valueX, finalY + 14, { align: 'right' });

    // Total - make it bold
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Total:', summaryX, finalY + 24);
    doc.text(order.total, valueX, finalY + 24, { align: 'right' });

    // Reset font
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    // Notes section (if any)
    if (order.notes) {
        const notesY = finalY + 40;
        doc.setFontSize(10);
        doc.setTextColor(...lightGray);
        doc.text('Notes:', 20, notesY);
        doc.setTextColor(...textColor);
        const notesLines = doc.splitTextToSize(order.notes, 170);
        doc.text(notesLines, 20, notesY + 7);
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(...lightGray);
    doc.text('Thank you for your business!', 105, pageHeight - 15, { align: 'center' });
    doc.text('Generated by CMS Full Form Dashboard', 105, pageHeight - 10, { align: 'center' });

    // Download the PDF
    doc.save(`Invoice-${order.id}.pdf`);
}

export function generatePrintableOrder(order: Order): void {
    // Create a new window for printing
    const printWindow = window.open('', '_blank', 'width=800,height=600');

    if (!printWindow) {
        alert('Please allow popups to print');
        return;
    }

    // Build the timeline HTML
    const timelineHtml = order.timeline.map((event, index) => `
        <div style="display: flex; gap: 12px; margin-bottom: 16px;">
            <div style="display: flex; flex-direction: column; align-items: center;">
                <div style="width: 32px; height: 32px; border-radius: 50%; background: ${index === order.timeline.length - 1 ? '#3b82f6' : '#22c55e'}; display: flex; align-items: center; justify-content: center; color: white; font-size: 14px;">
                    ${index === order.timeline.length - 1 ? '●' : '✓'}
                </div>
                ${index < order.timeline.length - 1 ? '<div style="width: 2px; flex: 1; background: #e5e7eb; min-height: 30px;"></div>' : ''}
            </div>
            <div style="flex: 1;">
                <p style="font-weight: 500; margin: 0; font-size: 14px;">${event.action}</p>
                <p style="color: #6b7280; margin: 4px 0 0; font-size: 12px;">${event.description}</p>
                <p style="color: #9ca3af; margin: 4px 0 0; font-size: 11px;">${event.time}</p>
            </div>
        </div>
    `).join('');

    // Build the items table HTML
    const itemsHtml = order.items.map(item => `
        <tr>
            <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">
                <p style="font-weight: 500; margin: 0;">${item.name}</p>
                <p style="color: #6b7280; margin: 4px 0 0; font-size: 12px;">SKU: ${item.sku}</p>
            </td>
            <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">${item.price}</td>
            <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.quantity}</td>
            <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: 500;">${item.total}</td>
        </tr>
    `).join('');

    // Build the print content
    const printContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order ${order.id} - Print View</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.5;
            color: #1f2937;
            background: white;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
        }
        
        @media print {
            body {
                padding: 20px;
            }
            
            .no-print {
                display: none !important;
            }
        }
        
        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 32px;
            padding-bottom: 24px;
            border-bottom: 2px solid #3b82f6;
        }
        
        .header-left h1 {
            font-size: 28px;
            font-weight: 700;
            color: #3b82f6;
            margin-bottom: 8px;
        }
        
        .header-left .order-id {
            font-size: 14px;
            color: #6b7280;
        }
        
        .header-right {
            text-align: right;
        }
        
        .header-right .status {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 500;
            text-transform: capitalize;
            margin-bottom: 8px;
            ${order.status === 'pending' ? 'background: #fef3c7; color: #92400e;' : ''}
            ${order.status === 'processing' ? 'background: #ede9fe; color: #6d28d9;' : ''}
            ${order.status === 'shipped' ? 'background: #dbeafe; color: #1d4ed8;' : ''}
            ${order.status === 'delivered' ? 'background: #d1fae5; color: #047857;' : ''}
        }
        
        .header-right .dates {
            font-size: 12px;
            color: #6b7280;
        }
        
        .section {
            margin-bottom: 32px;
        }
        
        .section-title {
            font-size: 16px;
            font-weight: 600;
            margin-bottom: 16px;
            color: #374151;
            padding-bottom: 8px;
            border-bottom: 1px solid #e5e7eb;
        }
        
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 24px;
        }
        
        .info-item {
            margin-bottom: 12px;
        }
        
        .info-label {
            font-size: 12px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 4px;
        }
        
        .info-value {
            font-size: 14px;
            font-weight: 500;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        
        th {
            background: #f9fafb;
            padding: 12px;
            text-align: left;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #6b7280;
            border-bottom: 2px solid #e5e7eb;
        }
        
        th:last-child, td:last-child {
            text-align: right;
        }
        
        th:nth-child(3), td:nth-child(3) {
            text-align: center;
        }
        
        .summary {
            display: flex;
            justify-content: flex-end;
            margin-top: 24px;
        }
        
        .summary-table {
            width: 250px;
        }
        
        .summary-row {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            font-size: 14px;
        }
        
        .summary-row.total {
            border-top: 2px solid #e5e7eb;
            font-weight: 700;
            font-size: 16px;
            padding-top: 12px;
            margin-top: 4px;
        }
        
        .notes {
            background: #f9fafb;
            padding: 16px;
            border-radius: 8px;
            font-size: 14px;
            color: #6b7280;
        }
        
        .footer {
            margin-top: 48px;
            padding-top: 24px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
        }
        
        .print-btn {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 12px 24px;
            background: #3b82f6;
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        
        .print-btn:hover {
            background: #2563eb;
        }
        
        @media print {
            .print-btn {
                display: none;
            }
        }
    </style>
</head>
<body>
    <button class="print-btn no-print" onclick="window.print()">🖨️ Print Order</button>
    
    <div class="header">
        <div class="header-left">
            <h1>ORDER DETAILS</h1>
            <p class="order-id">Order #${order.id}</p>
        </div>
        <div class="header-right">
            <span class="status">${order.status}</span>
            <p class="dates">Created: ${order.createdAt}</p>
            <p class="dates">Updated: ${order.updatedAt}</p>
        </div>
    </div>

    <div class="section">
        <h2 class="section-title">Customer Information</h2>
        <div class="info-grid">
            <div>
                <div class="info-item">
                    <div class="info-label">Customer Name</div>
                    <div class="info-value">${order.customer.name}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Email</div>
                    <div class="info-value">${order.customer.email}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Phone</div>
                    <div class="info-value">${order.customer.phone}</div>
                </div>
            </div>
            <div>
                <div class="info-item">
                    <div class="info-label">Shipping Address</div>
                    <div class="info-value">${order.shippingAddress}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Payment Method</div>
                    <div class="info-value">${order.paymentMethod}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Payment Status</div>
                    <div class="info-value">${order.paymentStatus}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2 class="section-title">Order Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                ${itemsHtml}
            </tbody>
        </table>
        
        <div class="summary">
            <div class="summary-table">
                <div class="summary-row">
                    <span>Subtotal</span>
                    <span>${order.subtotal}</span>
                </div>
                <div class="summary-row">
                    <span>Shipping</span>
                    <span>${order.shipping}</span>
                </div>
                <div class="summary-row">
                    <span>Tax</span>
                    <span>${order.tax}</span>
                </div>
                <div class="summary-row total">
                    <span>Total</span>
                    <span>${order.total}</span>
                </div>
            </div>
        </div>
    </div>

    ${order.timeline.length > 0 ? `
    <div class="section">
        <h2 class="section-title">Order Timeline</h2>
        ${timelineHtml}
    </div>
    ` : ''}

    ${order.notes ? `
    <div class="section">
        <h2 class="section-title">Notes</h2>
        <div class="notes">${order.notes}</div>
    </div>
    ` : ''}

    <div class="footer">
        <p>Thank you for your business!</p>
        <p>Generated by CMS Full Form Dashboard • ${new Date().toLocaleDateString()}</p>
    </div>
</body>
</html>
    `;

    printWindow.document.write(printContent);
    printWindow.document.close();
}
